
// This file was autogenerated by PeakRDL-uvm
package UART_CTRL_REGS_uvm;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // reg - UART_CTRL_REGS::UART_CPB
    class UART_CTRL_REGS__UART_CPB extends uvm_reg;
        rand uvm_reg_field CPB;

        function new(string name = "UART_CTRL_REGS__UART_CPB");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.CPB = new("CPB");
            this.CPB.configure(this, 32, 0, "RW", 0, 'h1, 1, 1, 0);
        endfunction : build
    endclass : UART_CTRL_REGS__UART_CPB

    // reg - UART_CTRL_REGS::UART_STP
    class UART_CTRL_REGS__UART_STP extends uvm_reg;
        rand uvm_reg_field STP;

        function new(string name = "UART_CTRL_REGS__UART_STP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.STP = new("STP");
            this.STP.configure(this, 2, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : UART_CTRL_REGS__UART_STP

    // reg - UART_CTRL_REGS::UART_RDR
    class UART_CTRL_REGS__UART_RDR extends uvm_reg;
        rand uvm_reg_field RD;

        function new(string name = "UART_CTRL_REGS__UART_RDR");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.RD = new("RD");
            this.RD.configure(this, 8, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : UART_CTRL_REGS__UART_RDR

    // reg - UART_CTRL_REGS::UART_TDR
    class UART_CTRL_REGS__UART_TDR extends uvm_reg;
        rand uvm_reg_field TD;

        function new(string name = "UART_CTRL_REGS__UART_TDR");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.TD = new("TD");
            this.TD.configure(this, 8, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : UART_CTRL_REGS__UART_TDR

    // reg - UART_CTRL_REGS::UART_CFG
    class UART_CTRL_REGS__UART_CFG extends uvm_reg;
        rand uvm_reg_field TX_START;
        rand uvm_reg_field RD_RECIEVED;
        rand uvm_reg_field TX_COMPLETE;

        function new(string name = "UART_CTRL_REGS__UART_CFG");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.TX_START = new("TX_START");
            this.TX_START.configure(this, 1, 0, "RW", 1, 'h0, 1, 1, 0);
            this.RD_RECIEVED = new("RD_RECIEVED");
            this.RD_RECIEVED.configure(this, 1, 1, "RW", 1, 'h0, 1, 1, 0);
            this.TX_COMPLETE = new("TX_COMPLETE");
            this.TX_COMPLETE.configure(this, 1, 2, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : UART_CTRL_REGS__UART_CFG

    // addrmap - UART_CTRL_REGS
    class UART_CTRL_REGS extends uvm_reg_block;
        rand UART_CTRL_REGS__UART_CPB UART_CPB;
        rand UART_CTRL_REGS__UART_STP UART_STP;
        rand UART_CTRL_REGS__UART_RDR UART_RDR;
        rand UART_CTRL_REGS__UART_TDR UART_TDR;
        rand UART_CTRL_REGS__UART_CFG UART_CFG;

        function new(string name = "UART_CTRL_REGS");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_LITTLE_ENDIAN);
            this.UART_CPB = new("UART_CPB");
            this.UART_CPB.configure(this);

            this.UART_CPB.build();
            this.default_map.add_reg(this.UART_CPB, 'h0);
            this.UART_STP = new("UART_STP");
            this.UART_STP.configure(this);

            this.UART_STP.build();
            this.default_map.add_reg(this.UART_STP, 'h4);
            this.UART_RDR = new("UART_RDR");
            this.UART_RDR.configure(this);

            this.UART_RDR.build();
            this.default_map.add_reg(this.UART_RDR, 'h8);
            this.UART_TDR = new("UART_TDR");
            this.UART_TDR.configure(this);

            this.UART_TDR.build();
            this.default_map.add_reg(this.UART_TDR, 'hc);
            this.UART_CFG = new("UART_CFG");
            this.UART_CFG.configure(this);

            this.UART_CFG.build();
            this.default_map.add_reg(this.UART_CFG, 'h10);
        endfunction : build
    endclass : UART_CTRL_REGS

endpackage: UART_CTRL_REGS_uvm
