// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module UART_CTRL_REGS (
        input wire clk,
        input wire rst,

        input wire s_apb_psel,
        input wire s_apb_penable,
        input wire s_apb_pwrite,
        input wire [4:0] s_apb_paddr,
        input wire [31:0] s_apb_pwdata,
        output logic s_apb_pready,
        output logic [31:0] s_apb_prdata,
        output logic s_apb_pslverr,

        input UART_CTRL_REGS_pkg::UART_CTRL_REGS__in_t hwif_in,
        output UART_CTRL_REGS_pkg::UART_CTRL_REGS__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [4:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Request
    logic is_active;
    always_ff @(posedge clk) begin
        if(rst) begin
            is_active <= '0;
            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
        end else begin
            if(~is_active) begin
                if(s_apb_psel) begin
                    is_active <= '1;
                    cpuif_req <= '1;
                    cpuif_req_is_wr <= s_apb_pwrite;
                    cpuif_addr <= {s_apb_paddr[4:2], 2'b0};
                    cpuif_wr_data <= s_apb_pwdata;
                end
            end else begin
                cpuif_req <= '0;
                if(cpuif_rd_ack || cpuif_wr_ack) begin
                    is_active <= '0;
                end
            end
        end
    end
    assign cpuif_wr_biten = '1;

    // Response
    assign s_apb_pready = cpuif_rd_ack | cpuif_wr_ack;
    assign s_apb_prdata = cpuif_rd_data;
    assign s_apb_pslverr = cpuif_rd_err | cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic UART_CPB;
        logic UART_STP;
        logic UART_RDR;
        logic UART_TDR;
        logic UART_CFG;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic [4:0] decoded_addr;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_valid_rw;
        is_valid_addr = '1; // No valid address check
        is_valid_rw = '1; // No valid RW check
        decoded_reg_strb.UART_CPB = cpuif_req_masked & (cpuif_addr == 5'h0);
        decoded_reg_strb.UART_STP = cpuif_req_masked & (cpuif_addr == 5'h4);
        decoded_reg_strb.UART_RDR = cpuif_req_masked & (cpuif_addr == 5'h8) & !cpuif_req_is_wr;
        decoded_reg_strb.UART_TDR = cpuif_req_masked & (cpuif_addr == 5'hc);
        decoded_reg_strb.UART_CFG = cpuif_req_masked & (cpuif_addr == 5'h10);
        decoded_err = '0;
    end

    // Pass down signals to next stage
    assign decoded_addr = cpuif_addr;
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } CPB;
        } UART_CPB;
        struct {
            struct {
                logic [1:0] next;
                logic load_next;
            } STP;
        } UART_STP;
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } RD;
        } UART_RDR;
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } TD;
        } UART_TDR;
        struct {
            struct {
                logic next;
                logic load_next;
            } TX_START;
            struct {
                logic next;
                logic load_next;
            } RD_RECIEVED;
            struct {
                logic next;
                logic load_next;
            } TX_COMPLETE;
        } UART_CFG;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic [31:0] value;
            } CPB;
        } UART_CPB;
        struct {
            struct {
                logic [1:0] value;
            } STP;
        } UART_STP;
        struct {
            struct {
                logic [7:0] value;
            } RD;
        } UART_RDR;
        struct {
            struct {
                logic [7:0] value;
            } TD;
        } UART_TDR;
        struct {
            struct {
                logic value;
            } TX_START;
            struct {
                logic value;
            } RD_RECIEVED;
            struct {
                logic value;
            } TX_COMPLETE;
        } UART_CFG;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: UART_CTRL_REGS.UART_CPB.CPB
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.UART_CPB.CPB.value;
        load_next_c = '0;
        if(decoded_reg_strb.UART_CPB && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.UART_CPB.CPB.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.UART_CPB.CPB.next = next_c;
        field_combo.UART_CPB.CPB.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.UART_CPB.CPB.value <= 32'h1;
        end else begin
            if(field_combo.UART_CPB.CPB.load_next) begin
                field_storage.UART_CPB.CPB.value <= field_combo.UART_CPB.CPB.next;
            end
        end
    end
    assign hwif_out.UART_CPB.CPB.value = field_storage.UART_CPB.CPB.value;
    // Field: UART_CTRL_REGS.UART_STP.STP
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.UART_STP.STP.value;
        load_next_c = '0;
        if(decoded_reg_strb.UART_STP && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.UART_STP.STP.value & ~decoded_wr_biten[1:0]) | (decoded_wr_data[1:0] & decoded_wr_biten[1:0]);
            load_next_c = '1;
        end
        field_combo.UART_STP.STP.next = next_c;
        field_combo.UART_STP.STP.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.UART_STP.STP.value <= 2'h0;
        end else begin
            if(field_combo.UART_STP.STP.load_next) begin
                field_storage.UART_STP.STP.value <= field_combo.UART_STP.STP.next;
            end
        end
    end
    assign hwif_out.UART_STP.STP.value = field_storage.UART_STP.STP.value;
    // Field: UART_CTRL_REGS.UART_RDR.RD
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.UART_RDR.RD.value;
        load_next_c = '0;
        
        // HW Write
        next_c = hwif_in.UART_RDR.RD.next;
        load_next_c = '1;
        field_combo.UART_RDR.RD.next = next_c;
        field_combo.UART_RDR.RD.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.UART_RDR.RD.value <= 8'h0;
        end else begin
            if(field_combo.UART_RDR.RD.load_next) begin
                field_storage.UART_RDR.RD.value <= field_combo.UART_RDR.RD.next;
            end
        end
    end
    assign hwif_out.UART_RDR.RD.value = field_storage.UART_RDR.RD.value;
    // Field: UART_CTRL_REGS.UART_TDR.TD
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.UART_TDR.TD.value;
        load_next_c = '0;
        if(decoded_reg_strb.UART_TDR && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.UART_TDR.TD.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.UART_TDR.TD.next = next_c;
        field_combo.UART_TDR.TD.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.UART_TDR.TD.value <= 8'h0;
        end else begin
            if(field_combo.UART_TDR.TD.load_next) begin
                field_storage.UART_TDR.TD.value <= field_combo.UART_TDR.TD.next;
            end
        end
    end
    assign hwif_out.UART_TDR.TD.value = field_storage.UART_TDR.TD.value;
    // Field: UART_CTRL_REGS.UART_CFG.TX_START
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.UART_CFG.TX_START.value;
        load_next_c = '0;
        if(decoded_reg_strb.UART_CFG && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.UART_CFG.TX_START.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end else if(hwif_in.UART_CFG.TX_START.hwclr) begin // HW Clear
            next_c = '0;
            load_next_c = '1;
        end
        field_combo.UART_CFG.TX_START.next = next_c;
        field_combo.UART_CFG.TX_START.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.UART_CFG.TX_START.value <= 1'h0;
        end else begin
            if(field_combo.UART_CFG.TX_START.load_next) begin
                field_storage.UART_CFG.TX_START.value <= field_combo.UART_CFG.TX_START.next;
            end
        end
    end
    assign hwif_out.UART_CFG.TX_START.value = field_storage.UART_CFG.TX_START.value;
    // Field: UART_CTRL_REGS.UART_CFG.RD_RECIEVED
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.UART_CFG.RD_RECIEVED.value;
        load_next_c = '0;
        if(hwif_in.UART_CFG.RD_RECIEVED.hwset) begin // HW Set
            next_c = '1;
            load_next_c = '1;
        end else if(decoded_reg_strb.UART_CFG && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.UART_CFG.RD_RECIEVED.value & ~decoded_wr_biten[1:1]) | (decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
            load_next_c = '1;
        end
        field_combo.UART_CFG.RD_RECIEVED.next = next_c;
        field_combo.UART_CFG.RD_RECIEVED.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.UART_CFG.RD_RECIEVED.value <= 1'h0;
        end else begin
            if(field_combo.UART_CFG.RD_RECIEVED.load_next) begin
                field_storage.UART_CFG.RD_RECIEVED.value <= field_combo.UART_CFG.RD_RECIEVED.next;
            end
        end
    end
    assign hwif_out.UART_CFG.RD_RECIEVED.value = field_storage.UART_CFG.RD_RECIEVED.value;
    // Field: UART_CTRL_REGS.UART_CFG.TX_COMPLETE
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.UART_CFG.TX_COMPLETE.value;
        load_next_c = '0;
        if(hwif_in.UART_CFG.TX_COMPLETE.hwset) begin // HW Set
            next_c = '1;
            load_next_c = '1;
        end else if(decoded_reg_strb.UART_CFG && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.UART_CFG.TX_COMPLETE.value & ~decoded_wr_biten[2:2]) | (decoded_wr_data[2:2] & decoded_wr_biten[2:2]);
            load_next_c = '1;
        end
        field_combo.UART_CFG.TX_COMPLETE.next = next_c;
        field_combo.UART_CFG.TX_COMPLETE.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.UART_CFG.TX_COMPLETE.value <= 1'h0;
        end else begin
            if(field_combo.UART_CFG.TX_COMPLETE.load_next) begin
                field_storage.UART_CFG.TX_COMPLETE.value <= field_combo.UART_CFG.TX_COMPLETE.next;
            end
        end
    end
    assign hwif_out.UART_CFG.TX_COMPLETE.value = field_storage.UART_CFG.TX_COMPLETE.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic [4:0] rd_mux_addr;
    assign rd_mux_addr = decoded_addr;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_data_var = '0;
        if(rd_mux_addr == 5'h0) begin
            readback_data_var[31:0] = field_storage.UART_CPB.CPB.value;
        end
        if(rd_mux_addr == 5'h4) begin
            readback_data_var[1:0] = field_storage.UART_STP.STP.value;
        end
        if(rd_mux_addr == 5'h8) begin
            readback_data_var[7:0] = field_storage.UART_RDR.RD.value;
        end
        if(rd_mux_addr == 5'hc) begin
            readback_data_var[7:0] = field_storage.UART_TDR.TD.value;
        end
        if(rd_mux_addr == 5'h10) begin
            readback_data_var[0] = field_storage.UART_CFG.TX_START.value;
            readback_data_var[1] = field_storage.UART_CFG.RD_RECIEVED.value;
            readback_data_var[2] = field_storage.UART_CFG.TX_COMPLETE.value;
        end
        readback_data = readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
