// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package UART_CTRL_REGS_pkg;

    localparam UART_CTRL_REGS_DATA_WIDTH = 32;
    localparam UART_CTRL_REGS_MIN_ADDR_WIDTH = 5;
    localparam UART_CTRL_REGS_SIZE = 'h14;

    typedef struct {
        logic [7:0] next;
    } UART_CTRL_REGS__UART_RDR__RD__in_t;

    typedef struct {
        UART_CTRL_REGS__UART_RDR__RD__in_t RD;
    } UART_CTRL_REGS__UART_RDR__in_t;

    typedef struct {
        logic hwclr;
    } UART_CTRL_REGS__UART_CFG__TX_START__in_t;

    typedef struct {
        logic hwset;
    } UART_CTRL_REGS__UART_CFG__RD_RECIEVED__in_t;

    typedef struct {
        logic hwset;
    } UART_CTRL_REGS__UART_CFG__TX_COMPLETE__in_t;

    typedef struct {
        UART_CTRL_REGS__UART_CFG__TX_START__in_t TX_START;
        UART_CTRL_REGS__UART_CFG__RD_RECIEVED__in_t RD_RECIEVED;
        UART_CTRL_REGS__UART_CFG__TX_COMPLETE__in_t TX_COMPLETE;
    } UART_CTRL_REGS__UART_CFG__in_t;

    typedef struct {
        UART_CTRL_REGS__UART_RDR__in_t UART_RDR;
        UART_CTRL_REGS__UART_CFG__in_t UART_CFG;
    } UART_CTRL_REGS__in_t;

    typedef struct {
        logic [31:0] value;
    } UART_CTRL_REGS__UART_CPB__CPB__out_t;

    typedef struct {
        UART_CTRL_REGS__UART_CPB__CPB__out_t CPB;
    } UART_CTRL_REGS__UART_CPB__out_t;

    typedef struct {
        logic [1:0] value;
    } UART_CTRL_REGS__UART_STP__STP__out_t;

    typedef struct {
        UART_CTRL_REGS__UART_STP__STP__out_t STP;
    } UART_CTRL_REGS__UART_STP__out_t;

    typedef struct {
        logic [7:0] value;
    } UART_CTRL_REGS__UART_RDR__RD__out_t;

    typedef struct {
        UART_CTRL_REGS__UART_RDR__RD__out_t RD;
    } UART_CTRL_REGS__UART_RDR__out_t;

    typedef struct {
        logic [7:0] value;
    } UART_CTRL_REGS__UART_TDR__TD__out_t;

    typedef struct {
        UART_CTRL_REGS__UART_TDR__TD__out_t TD;
    } UART_CTRL_REGS__UART_TDR__out_t;

    typedef struct {
        logic value;
    } UART_CTRL_REGS__UART_CFG__TX_START__out_t;

    typedef struct {
        logic value;
    } UART_CTRL_REGS__UART_CFG__RD_RECIEVED__out_t;

    typedef struct {
        logic value;
    } UART_CTRL_REGS__UART_CFG__TX_COMPLETE__out_t;

    typedef struct {
        UART_CTRL_REGS__UART_CFG__TX_START__out_t TX_START;
        UART_CTRL_REGS__UART_CFG__RD_RECIEVED__out_t RD_RECIEVED;
        UART_CTRL_REGS__UART_CFG__TX_COMPLETE__out_t TX_COMPLETE;
    } UART_CTRL_REGS__UART_CFG__out_t;

    typedef struct {
        UART_CTRL_REGS__UART_CPB__out_t UART_CPB;
        UART_CTRL_REGS__UART_STP__out_t UART_STP;
        UART_CTRL_REGS__UART_RDR__out_t UART_RDR;
        UART_CTRL_REGS__UART_TDR__out_t UART_TDR;
        UART_CTRL_REGS__UART_CFG__out_t UART_CFG;
    } UART_CTRL_REGS__out_t;
endpackage
